### PR TITLE
Security policy

### PR DESCRIPTION
**Pull request by Soapy7261**
🤷

### CODE REVIEW

**Comment by JulianVennen** [comment]
Copying a single line from the README is not really a good security policy.

**Comment by Soapy7261** [comment]
well of course it'd be more than that, but that just was just to show the idea

**Comment by JulianVennen** [comment]
This is not how you suggest something

**Comment by Soapy7261** [comment]
yeah my bad

**Comment by Soapy7261** [comment]
I'll make an issue next time, if that's how i should suggest something that is

**Pull request closed without merging**
